### ISSUE TITLE
Configuration for Rails 

### ISSUE THREAD

**Issue by yves-vogl** [resque/resque#1660]
Hi,

I know that resque supports more frameworks beside Ruby on Rails.
But maybe we can enhance the documentation for Rails users a little bit to match the [Rails Guides](https://edgeguides.rubyonrails.org/configuring.html#custom-configuration). 
Let me know if you agree and are open for a PR so that I can submit one.

I'd like to propose something like this:

config/resque.yml
```yaml
default: &default
  url: <%= ENV.fetch("REDIS_URL") { 'localhost:6379' } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
```

config/application.rb
```ruby
module App
  class Application < Rails::Application
    # (…)
    config.resque = config_for(:resque)
  end
end
```

config/initializers/resque.rb
```ruby
Resque.redis = Rails.configuration.resque['url']
```
