### ISSUE TITLE
undefined method `redis=' for Resque:Module (NoMethodError)

### ISSUE THREAD

**Issue by kristianmandrup** [resque/resque#590]
```
config/initializers/resque.rb:5:in `<top (required)>': undefined method `redis=' for Resque:Module (NoMethodError)
```

in Gemfile

``` ruby
gem 'redis',              '>= 2.2.1'
```

config/initializers/resque

``` ruby
rails_root =    Rails.root.to_s || ENV['RAILS_ROOT'] || File.dirname(__FILE__) + '/../..'
rails_env =     ENV['RAILS_ENV'] || 'development'

resque_config = YAML.load_file(rails_root + '/config/resque.yml')
Resque.redis = resque_config[rails_env] || 'localhost:6379'
```

config/resque.yml

``` yaml
development: localhost:6379
test: localhost:6379
staging: redis1.se.github.com:6379
fi: localhost:6379
production: redis1.ae.github.com:6379
```

I guess the README is out of sync!?
